version: "3.9"

services:
  redis:
    image: "redis:7.0.12-alpine"
    ports:
      - 6379:6379
  mongo:
    image: "mongo:6.0.8"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
  neo4j:
    image: "neo4j:5.9.0"
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
